### ISSUE TITLE
Add support for TLP 1.6

### ISSUE THREAD

**Issue by d4nj1** [d4nj1/TLPUI#135]
As first TLP 1.6 beta was released, TLPUI should add support for it.

DoD:

* Review changes in https://github.com/linrunner/TLP/releases/tag/1.6.0-beta.1
* Apply new configuration values and adjust existing ones
* Add basic test case

**Comment by d4nj1** [comment]
Hi,
I just released a new version that supports TLP 1.6
It would be nice if someone else would test and report back if you encounter any errors:

https://github.com/d4nj1/TLPUI/releases/tag/tlpui-1.6.0

Thanks in advance

**Comment by dretyuiop** [comment]
I encountered this error on Arch Linux, using tlpui package.

`gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/usr/lib/python3.11/site-packages/tlpui/icons/flags/fr_FR.png”: No such file or directory (4)`

It seems the png file for france flag is missing, I also tested with the release on github and had the same problem. So, I think you forgot to add the france flag png.

**Comment by d4nj1** [comment]
Thanks @dretyuiop ,
that was indeed missing. I forgot to add to git. I just committed so please retry if possible.

**Comment by dretyuiop** [comment]
It works perfectly. Thanks for your time and effort building this :)

**Comment by d4nj1** [comment]
Project is compatible with TLP 1.6 now. Flathub build system will release the new version soon.
